    // 2-component swizzles
    vec2 xx() const;
    vec2 xy() const;
    vec2 yx() const;
    vec2 yy() const;
    // 3-component swizzles
    vec3 xxx() const;
    vec3 xxy() const;
    vec3 xyx() const;
    vec3 xyy() const;
    vec3 yxx() const;
    vec3 yxy() const;
    vec3 yyx() const;
    vec3 yyy() const;
    // 4-component swizzles
    vec4 xxxx() const;
    vec4 xxxy() const;
    vec4 xxyx() const;
    vec4 xxyy() const;
    vec4 xyxx() const;
    vec4 xyxy() const;
    vec4 xyyx() const;
    vec4 xyyy() const;
    vec4 yxxx() const;
    vec4 yxxy() const;
    vec4 yxyx() const;
    vec4 yxyy() const;
    vec4 yyxx() const;
    vec4 yyxy() const;
    vec4 yyyx() const;
    vec4 yyyy() const;


